openapi: 3.0.0
info:
  description: API documentation for the OKO endpoints
  version: 1.0.1
  title: OKO API
  contact:
    email: jonas.carlsen@knowit.no
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - description: Actual API
    url: https://tcuk58u5ge.execute-api.eu-central-1.amazonaws.com/staging/backend
tags:
  - name: partnere
    description: Calls available in  the /partnere/ endpoint
  - name: uttak
    description: Calls available in the /uttak/ endpoint
  - name: uttaksdata
    description: Calls available in the /uttaksdata/ endpoint
  - name: stasjoner
    description: Calls available in the /stasjoner/ endpoint
  - name: pickups
    description: Calls available in the /pickups/ endpoint
  - name: requests
    description: Calls available in the /requests/ endpoint
#  - name: reg-admin
#    description: Calls available for reg admins
#  - name: reuse-stasjon
#    description: Calls available for reuse stasjon workers.
#  - name: partner
#    description: Calls available for partnere. Can only access uttaksdata that belong to said partner.
#  - name: everyone
#    description: Calls available for unauthorized users
paths:
  /partnere/{id}:
    $ref: "./partner/partnereId.yaml"
  /partnere:
    $ref: "./partner/partnere.yaml"
  /stasjoner:
    $ref: "./stasjon/stasjoner.yaml"
  /stasjoner{id}:
    $ref: "./stasjon/stasjonerId.yaml"
  /uttaksdata:
    $ref: "./uttaksdata/uttaksdata.yaml"
  /uttaksdata{id}:
    $ref: "./uttaksdata/uttaksdataId.yaml"
  /uttak:
    $ref: "./calendar/uttak.yaml"
  /uttak/{id}:
    $ref: "./calendar/uttaksId.yaml"
  /pickups/:
    $ref: "./no.oslokommune.ombruk.pickup/pickups.yaml"
  /pickups/{id}:
    $ref: "./no.oslokommune.ombruk.pickup/pickupsId.yaml"
  /requests/:
    $ref: "./request/requests.yaml"

components:
  schemas:
    PartnerPost:
      $ref: "./partner/schemas/partnerPost.yaml"
    Partner:
      $ref: "./partner/schemas/partner.yaml"
    PartnerPatch:
      $ref: "./partner/schemas/partnerPatch.yaml"
    Report:
      $ref: "./uttaksdata/schemas/uttaksdata.yaml"
    ReportPatch:
      $ref: "./uttaksdata/schemas/uttaksdataPatch.yaml"
    Stasjon:
      $ref: "./stasjon/schemas/stasjon.yaml"
    StasjonPost:
      $ref: "./stasjon/schemas/stasjonPost.yaml"
    StasjonPatch:
      $ref: "./stasjon/schemas/stasjonPatch.yaml"
    Uttak:
      $ref: "./calendar/schemas/uttak.yaml"
    UttakPatch:
      $ref: "./calendar/schemas/uttakPatch.yaml"
    UttakPost:
      $ref: "./calendar/schemas/uttakPost.yaml"
    GjentakelsesRegel:
      $ref: "./calendar/schemas/gjentakelsesRegel.yaml"
    GjentakelsesRegelPost:
      $ref: "./calendar/schemas/gjentakelsesRegelPost.yaml"
    PickupPost:
      $ref: "./no.oslokommune.ombruk.pickup/schemas/pickupPost.yaml"
    PickupPatch:
      $ref: "./no.oslokommune.ombruk.pickup/schemas/pickupPatch.yaml"
    Pickup:
      $ref: "./no.oslokommune.ombruk.pickup/schemas/no.oslokommune.ombruk.pickup.yaml"
    RequestPost:
      $ref: "./request/schemas/requestPost.yaml"
    Request:
      $ref: "./request/schemas/request.yaml"