openapi: 3.0.0
info:
  description: API documentation for the OKO endpoints
  version: 1.0.1
  title: OKO API
  contact:
    email: jonas.carlsen@knowit.no
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - description: Actual API
    url: https://tcuk58u5ge.execute-api.eu-central-1.amazonaws.com/staging/backend
tags:
  - name: partners
    description: Calls available in  the /partners/ endpoint
  - name: uttaks
    description: Calls available in the /uttaks/ endpoint
  - name: reports
    description: Calls available in the /reports/ endpoint
  - name: stasjoner
    description: Calls available in the /stasjoner/ endpoint
  - name: pickups
    description: Calls available in the /pickups/ endpoint
  - name: requests
    description: Calls available in the /requests/ endpoint
#  - name: reg-admin
#    description: Calls available for reg admins
#  - name: reuse-stasjon
#    description: Calls available for reuse stasjon workers.
#  - name: partner
#    description: Calls available for partners. Can only access reports that belong to said partner.
#  - name: everyone
#    description: Calls available for unauthorized users
paths:
  /partners/{id}:
    $ref: "./partner/partnersId.yaml"
  /partners:
    $ref: "./partner/partners.yaml"
  /stasjoner:
    $ref: "./stasjon/stasjoner.yaml"
  /stasjoner{id}:
    $ref: "./stasjon/stasjonerId.yaml"
  /reports:
    $ref: "./report/reports.yaml"
  /reports{id}:
    $ref: "./report/reportsId.yaml"
  /uttaks:
    $ref: "./calendar/uttaks.yaml"
  /uttaks/{id}:
    $ref: "./calendar/uttaksId.yaml"
  /pickups/:
    $ref: "./no.oslokommune.ombruk.pickup/pickups.yaml"
  /pickups/{id}:
    $ref: "./no.oslokommune.ombruk.pickup/pickupsId.yaml"
  /requests/:
    $ref: "./request/requests.yaml"

components:
  schemas:
    PartnerPost:
      $ref: "./partner/schemas/partnerPost.yaml"
    Partner:
      $ref: "./partner/schemas/partner.yaml"
    PartnerPatch:
      $ref: "./partner/schemas/partnerPatch.yaml"
    Report:
      $ref: "./report/schemas/report.yaml"
    ReportPatch:
      $ref: "./report/schemas/reportPatch.yaml"
    Stasjon:
      $ref: "./stasjon/schemas/stasjon.yaml"
    StasjonPost:
      $ref: "./stasjon/schemas/stasjonPost.yaml"
    StasjonPatch:
      $ref: "./stasjon/schemas/stasjonPatch.yaml"
    Uttak:
      $ref: "./calendar/schemas/uttak.yaml"
    UttakPatch:
      $ref: "./calendar/schemas/uttakPatch.yaml"
    UttakPost:
      $ref: "./calendar/schemas/uttakPost.yaml"
    RecurrenceRule:
      $ref: "./calendar/schemas/recurrenceRule.yaml"
    RecurrenceRulePost:
      $ref: "./calendar/schemas/recurrenceRulePost.yaml"
    PickupPost:
      $ref: "./no.oslokommune.ombruk.pickup/schemas/pickupPost.yaml"
    PickupPatch:
      $ref: "./no.oslokommune.ombruk.pickup/schemas/pickupPatch.yaml"
    Pickup:
      $ref: "./no.oslokommune.ombruk.pickup/schemas/no.oslokommune.ombruk.pickup.yaml"
    RequestPost:
      $ref: "./request/schemas/requestPost.yaml"
    Request:
      $ref: "./request/schemas/request.yaml"