version: '3.8'
services:
  calendar:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    links:
      - database
    ports:
      - 8080:8080
    volumes:
      - .:/srv/ombruk-backend
    environment:
      CALENDAR_JDBC_URL: "jdbc:postgresql://calendar-microservice_database_1/postgres"
      CALENDAR_DB_USER: "postgres"
      CALENDAR_DB_PASSWORD: "postgres"
      CALENDAR_DB_MIGRATIONS_LOCATION: filesystem:resources/db/migrations
  database:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres


volumes:
  db_data: