openapi: 3.0.0
servers:
  - description: Actual API
    url: https://tcuk58u5ge.execute-api.eu-central-1.amazonaws.com/backend/partner
info:
  description: API documentation for the OKO partners endpoint
  version: "1.0.1"
  title: OKO Partners
  contact:
    email: jonas.carlsen@knowit.no
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: reg-admin
    description: Calls available for reg admins
  - name: everyone
    description: Calls available for unauthorized users
paths:
  /partners/{id}:
    get:
      tags:
        - everyone
      summary: fetches partners
      operationId: getPartner
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "Partner matching ID"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Partner'
        '400':
          description: bad input parameter
        '404':
          description: Partner not found
        '500':
          description: Internal server error

    delete:
      tags:
        - reg-admin
      summary: Deletes a partner
      operationId: deletePartner
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Partner deleted successfully
        '400':
          description: Bad input parameter
        '500':
          description: Internal server error
        '404':
          description: ID not found

  /partners/:
    get:
      tags:
        - everyone
      summary: Gets all partners
      operationId: getPartners
      responses:
        '200':
          description: Returns all partners
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Partner'
        '500':
          description: Internal server error

    post:
      tags:
        - reg-admin
      summary: adds a partner
      operationId: addPartner
      description: Adds a partner to the database and to keycloak. Name must be unique.
      responses:
        '200':
          description: item created
          content:
            application/json:
              schema:
                type: integer
                format: int64
                description: The DB id of the stored partner
        '400':
          description: 'Bad partner body'
        '401':
          description: Unauthorized
        '403':
          description: Insufficient role privileges
        '409':
          description: A partner with that name already exists
        '422':
          description: Validation of partner body failed. Unprocessable entity
        '500':
          description: Internal server error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostPartner'

    patch:
      tags:
        - reg-admin
      summary: Updates a partner both in the database and in keycloak
      operationId: patchpartner
      description: |
        Updates a partner in both the database and in keycloak. ID cannot be
        changed and must correspond with an existing partner. Name must be unique.
      responses:
        '200':
          description: Partner updated
        '400':
          description: Bad request body
        '401':
          description: Unauthorized
        '403':
          description: Forbidden. Insufficient role permissions.
        '404':
          description: ID not found
        '409':
          description: A partner with that name already exists
        '422':
          description: Unprocessable request body. Validation of request body failed
        '500':
          description: Internal server error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchPartner'
components:
  schemas:
    PostPartner:
      type: object
      properties:
        name:
          type: string
          example: "Fretex"
          required: true
        description:
          type: string
          example: "Lorem ipsum..."
          required: true
        phone:
          type: string
          example: "+47 12345678"
          required: true
        email:
          type: string
          example: "example@example.com"
          required: true

    PatchPartner:
      type: object
      properties:
        id:
          type: integer
          format: int64
          required: true
        name:
          type: string
          example: "Fretex"
          required: false
        description:
          type: string
          example: "Lorem Ipsum..."
          required: false
        phone:
          type: string
          example: "+47 12345678"
          required: false
        email:
          type: string
          example: "example@example.com"
          required: false

    Partner:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: "Fretex"
        description:
          type: string
          example: "Lorem Ipsum..."
        phone:
          type: string
          example: "+47 12345678"
        email:
          type: string
          example: "example@example.com"