openapi: 3.0.0
servers:
  - description: Actual API
    url: https://tcuk58u5ge.execute-api.eu-central-1.amazonaws.com/staging/station
info:
  description: API documentation for the OKO stations endpoint
  version: "1.0.1"
  title: OKO Partners
  contact:
    email: jonas.carlsen@knowit.no
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: reg-admin
    description: Calls available for reg admins
  - name: everyone
    description: Calls available for unauthorized users
paths:
  /stations/{id}:
    get:
      tags:
        - everyone
      summary: fetches stations
      operationId: getStations
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "Station matching ID"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Station'
        '400':
          description: Bad input parameter
        '404':
          description: Station not found
        '500':
          description: Internal server error

    delete:
      tags:
        - reg-admin
      summary: Deletes a station
      operationId: deleteStation
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Station deleted successfully
        '400':
          description: Bad input parameter
        '401':
          description: Unauthorized
        '403':
          description: Insufficient role privileges
        '404':
          description: ID not found
        '500':
          description: Internal server error

  /stations/:
    get:
      tags:
        - everyone
      summary: Gets all stations
      operationId: getStations
      responses:
        '200':
          description: Returns all stations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Station'
        '500':
          description: Internal server error

    post:
      tags:
        - reg-admin
      summary: Adds a station
      operationId: addStation
      description: Adds a station to the database. Name must be unique. The stored Station object is returned if request is valid.
      responses:
        '200':
          description: item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Station'
        '400':
          description: 'Bad station body'
        '401':
          description: Unauthorized
        '403':
          description: Insufficient role privileges
        '409':
          description: "Name conflict"
        '500':
          description: Internal server error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StationPostForm'

    patch:
      tags:
        - reg-admin
      summary: Updates a station
      operationId: patchpartner
      description:
        |
        Updates a partner. ID cannot be changed and must correspond with an existing station. Name must be unique.
        The stored station object is returned if request is valid
      responses:
        '200':
          description: Station updated
        '400':
          description: Bad request body
        '401':
          description: Unauthorized
        '403':
          description: Insufficient role privileges
        '404':
          description: ID not found
        '409':
          description: Name conflict
        '500':
          description: Internal server error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStation'

components:
  schemas:

    StationUpdateForm:
      type: object
      properties:
        id:
          type: integer
          format: int64
          required: true
        name:
          type: string
          description: Must be unique
          example: "Ryen"
          required: false
        openingTime:
          type: time
          example: "08:00:00Z"
          required: false
        closingTime:
          type: time
          example: "21:00:00Z"
          required: false

    StationPostForm:
      type: object
      properties:
        name:
          type: string
          description: Must be unique
          example: "Ryen"
          required: true
        openingTime:
          type: time
          example: "08:00:00Z"
          required: true
        closingTime:
          type: time
          example: "21:00:00Z"
          required: true

    Station:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: "Haraldrud"
        openingTime:
          type: time
          example: "09:00:00Z"
        closingTime:
          type: time
          example: "20:00:00Z"