openapi: 3.0.0
servers:
  - description: Actual API
    url: https://tcuk58u5ge.execute-api.eu-central-1.amazonaws.com/backend/reports
info:
  description: API documentation for the OKO reporting endpoint
  version: "1.0.1"
  title: OKO Reports
  contact:
    email: jonas.carlsen@knowit.no
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: reg-admin
    description: Calls available for reg admins
  - name: reuse-station
    description: Calls available for reuse station workers.
  - name: partner
    description: Calls available for partners. Can only access reports that belong to said partner.
  - name: everyone
    description: Calls available for unauthorized users
paths:
  /reports/{id}:
    get:
      tags:
        - everyone
      summary: fetches a report
      operationId: getReport
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "Report matching ID"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
        '400':
          description: Bad input parameter
        '404':
          description: Report not found
        '500':
          description: Internal server error

  /reports/:
    get:
      tags:
        - everyone
      summary: Gets all reports
      operationId: getReports
      description: |
        Get functionality that allows for getting reports. If called without parameters, all reports are returned.
        Each parameter that is passed will be used to filter the output. For instance, one can GET reports within
        a range by specifying from-date and to-date.
      parameters:
        - in: query
          name: event-id
          description: Get the report that corresponds to the specified event ID.
          required: false
          schema:
            type: integer
            format: int64
          example: 1
        - in: query
          name: station-id
          description: Only get reports belonging at the specified Station ID.
          required: false
          schema:
            type: integer
            format: int64
            example: 2
        - in: query
          name: partner-id
          description: Only get reports belonging to specified partner ID.
          required: false
          schema:
            type: integer
            format: int64
            example: 3
        - in: query
          name: from-date
          description: Get reports from the specified date and time.
          required: false
          schema:
            type: string
            format: date-time
            example: "2020-07-10T13:17:39Z"
        - in: query
          name: to-date
          description: Get reports until the specified date and time.
          required: false
          schema:
            type: string
            format: date-time
            example: "2020-07-20T13:17:39Z"
      responses:
        '200':
          description: Returns all reports
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Report'
        '500':
          description: Internal server error

    patch:
      tags:
        - reg-admin
        - reuse-station
        - partner
      summary: Sets the weight of a report
      operationId: patchWeight
      description: |
        Updates the weight of a report. When weight is updated, it's reportedDateTime field is also updated.
        Although partners can call this endpoint, they are only able to update reports that belong to their corresponding
        partner ID.
      responses:
        '200':
          description: Partner updated
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Report'
        '400':
          description: Bad request body
        '401':
          description: Unauthorized
        '403':
          description: Insufficient privileges. Is returned when a partner attempts to alter resources that they do not own.
        '404':
          description: ID not found
        '500':
          description: Internal server error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportUpdateForm'
components:
  schemas:

    Report:
      type: object
      properties:
        reportID:
          type: integer
          format: int64
          example: 1
        eventID:
          type: integer
          format: int64
          example: 1
        partnerID:
          type: integer
          format: int64
          example: 2
        stationID:
          type: integer
          format: int64
          example: 4
        startDateTime:
          type: string
          format: date-time
          example: "2020-07-13T15:00:00Z"
        endDateTime:
          type: string
          format: date-time
          example: "2020-07-13T17:00:00Z"
        weight:
          type: integer
          format: int64
        reportedDateTime:
          type: string
          format: date-time
          example: "2020-07-13T17:15:33Z"

    ReportUpdateForm:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
          required: true
        weight:
          type: integer
          format: int64
          example: 50
          required: true